swim_graph/parsing/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('upload/',
         views.upload_file_view,
         name='upload'),
    path('report_setup/<int:session_id>/',
         views.report_setup_view,
         name='report_setup'),
    path('sessions/',
         views.sessions_list_view,
         name='sessions_list'),
    path('sessions/<int:session_id>/',
         views.session_results_view,
         name='session_results'),
]

swim_graph/swim_graph/urls.py
"""swim_graph URL Configuration"""
from django.contrib import admin
from django.urls import path, include
from .views import home_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('parsing/', include('parsing.urls')),
]

swim_graph/parsing/models.py
"""parsing Models"""
from datetime import time
from django.db import models

from swim_graph_utils.constants import (
    PoolLength, SwimLength
)


class ParsingSession(models.Model):
    """Сессии парсинга."""

    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата создания сессии',
        db_comment='Дата создания сессии',
    )
    file_name = models.CharField(
        max_length=256,
        null=False,
        verbose_name='Название файла',
        db_comment='Название файла',
    )
    link_video = models.TextField(
        verbose_name='Ссылка на видео',
        db_comment='Ссылка на видео',
    )
    pool_length = models.CharField(
        max_length=4,
        choices=PoolLength.choices(),
        default=PoolLength.LONG.value,
        verbose_name='Длина бассейна',
        db_comment='Длина бассейна',
    )
    swim_length = models.CharField(
        max_length=5,
        choices=SwimLength.choices(),
        default=SwimLength.ONE_HUNDRED_METERS.value,
        verbose_name='Длина заплыва',
        db_comment='Длина заплыва',
    )

    def __str__(self) -> str:
        return f'Сессия парсинга: {self.file_name} от {self.created}'

    class Meta:
        verbose_name = 'сессию парсинга'
        verbose_name_plural = 'Сессии парсинга'


class ProtocolData(models.Model):
    """Данные об участниках заплывов из стартового и финального протоколов."""

    parsing_session = models.ForeignKey(
        ParsingSession,
        on_delete=models.CASCADE,
        verbose_name='Сессия парсинга',
        db_comment='Сессия парсинга',
    )
    initials = models.CharField(
        max_length=64,
        null=False,
        default='Ошибка при парсинге',
        verbose_name='Фамилия Имя',
        db_comment='Фамилия Имя',
    )
    year_of_birth = models.IntegerField(
        null=True,
        blank=True,
        verbose_name='Год рождения',
        db_comment='Год рождения',
    )
    final_category = models.CharField(
        max_length=24,
        null=True,
        blank=True,
        verbose_name='Категория финала',
        db_comment='Категория финала',
    )
    start_position = models.IntegerField(
        null=True,
        blank=True,
        verbose_name='Стартовая позиция (№ п.п.)',
        db_comment='Стартовая позиция (№ п.п.)',
    )
    final_position = models.IntegerField(
        null=True,
        blank=True,
        verbose_name='Финишная позиция (место)',
        db_comment='Финишная позиция (место)',
    )
    reaction_time = models.TimeField(
        null=True,
        blank=True,
        verbose_name='Время реакции',
        db_comment='Время реакции',
    )
    result = models.TimeField(
        null=False,
        default=time(0, 0),
        verbose_name="Результат",
        db_comment='Результат',
    )
    points = models.IntegerField(
        null=True,
        blank=True,
        verbose_name='Очки',
        db_comment='Очки',
    )

    def __str__(self) -> str:
        return f'{self.initials}: {self.final_position}-е место'

    class Meta:
        verbose_name = 'данные по заплыву'
        verbose_name_plural = 'Данные по заплывам'


class SwimSplitTime(models.Model):
    """Время по участникам на промежуточных дистанциях."""

    protocol_data = models.ForeignKey(
        ProtocolData,
        on_delete=models.CASCADE,
        verbose_name='Данные заплыва',
        db_comment='Данные заплыва',
    )
    distance = models.IntegerField(
        null=False,
        verbose_name='Дистанция',
        db_comment='Дистанция',
    )
    split_time = models.TimeField(
        null=True,
        blank=True,
        verbose_name='Время на промежуточной дистанции',
        db_comment='Время на промежуточной дистанции',
    )

    def __str__(self) -> str:
        return f'{self.distance} м - {self.split_time}'

    class Meta:
        verbose_name = 'Время на промежуточной дистанции'
        verbose_name_plural = 'Время на промежуточных дистанциях'


class StartDistance(models.Model):
    """Настройки для стартого отрезка."""

    parsing_session = models.ForeignKey(
        ParsingSession,
        on_delete=models.CASCADE,
        verbose_name='Сессия парсинга',
        db_comment='Сессия парсинга',
    )
    status = models.BooleanField(
        default=True,
        null=False,
        verbose_name='Статус',
        db_comment='Статус',
    )
    data = models.JSONField(
        default=dict,
        verbose_name='Данные',
        db_comment='Данные'
    )

    def __str__(self) -> str:
        return f'Стартовый отрезок (статус): {self.status}'

    class Meta:
        verbose_name = 'настройку для статрового отрезка'
        verbose_name_plural = 'Настройки для статрового отрезка'


class AverageSpeed(models.Model):
    """Настройки для средней скорости."""

    parsing_session = models.ForeignKey(
        ParsingSession,
        on_delete=models.CASCADE,
        verbose_name='Сессия парсинга',
        db_comment='Сессия парсинга',
    )
    status = models.BooleanField(
        default=True,
        null=False,
        verbose_name='Статус',
        db_comment='Статус',
    )

    def __str__(self) -> str:
        return f'Средняя скорость (статус): {self.status}'

    class Meta:
        verbose_name = 'настройку для средней скорости'
        verbose_name_plural = 'Настройки для средней скорости'


class NumberCycles(models.Model):
    """Настройки для кол-ва циклов на лучшем отрезке."""

    parsing_session = models.ForeignKey(
        ParsingSession,
        on_delete=models.CASCADE,
        verbose_name='Сессия парсинга',
        db_comment='Сессия парсинга',
    )
    status = models.BooleanField(
        default=True,
        null=False,
        verbose_name='Статус',
        db_comment='Статус',
    )
    data = models.JSONField(
        default=dict,
        verbose_name='Данные',
        db_comment='Данные'
    )

    def __str__(self) -> str:
        return f'Кол-во циклов на лучшем отрезке (статус): {self.status}'

    class Meta:
        verbose_name = 'настройку для кол-во циклов на лучшем отрезке'
        verbose_name_plural = 'Настройки для кол-ва циклов на лучшем отрезке'


class Pace(models.Model):
    """Настройки для темпа на лучшем отрезке."""

    parsing_session = models.ForeignKey(
        ParsingSession,
        on_delete=models.CASCADE,
        verbose_name='Сессия парсинга',
        db_comment='Сессия парсинга',
    )
    status = models.BooleanField(
        default=True,
        null=False,
        verbose_name='Статус',
        db_comment='Статус',
    )
    data = models.JSONField(
        default=dict,
        verbose_name='Данные',
        db_comment='Данные'
    )

    def __str__(self) -> str:
        return f'Темп на лучшем отрезке (статус): {self.status}'

    class Meta:
        verbose_name = 'настройку для темпа на лучшем отрезке'
        verbose_name_plural = 'Настройки для темпа на лучшем отрезке'


class SpeedDrop(models.Model):
    """Настройки для падения скорости."""

    parsing_session = models.ForeignKey(
        ParsingSession,
        on_delete=models.CASCADE,
        verbose_name='Сессия парсинга',
        db_comment='Сессия парсинга',
    )
    status = models.BooleanField(
        default=True,
        null=False,
        verbose_name='Статус',
        db_comment='Статус',
    )

    def __str__(self) -> str:
        return f'Падение скорости (статус): {self.status}'

    class Meta:
        verbose_name = 'настройку для падения скорости'
        verbose_name_plural = 'Настройки для падения скорости'


class LeaderGap(models.Model):
    """Настройки для отставания от лидера."""

    parsing_session = models.ForeignKey(
        ParsingSession,
        on_delete=models.CASCADE,
        verbose_name='Сессия парсинга',
        db_comment='Сессия парсинга',
    )
    status = models.BooleanField(
        default=True,
        null=False,
        verbose_name='Статус',
        db_comment='Статус',
    )

    def __str__(self) -> str:
        return f'Отставание от лидера (статус): {self.status}'

    class Meta:
        verbose_name = 'настройку для отставания от лидера'
        verbose_name_plural = 'Настройки для отставания от лидера'


class UnderwaterPart(models.Model):
    """Настройки для подводной части."""

    parsing_session = models.ForeignKey(
        ParsingSession,
        on_delete=models.CASCADE,
        verbose_name='Сессия парсинга',
        db_comment='Сессия парсинга',
    )
    status = models.BooleanField(
        default=True,
        null=False,
        verbose_name='Статус',
        db_comment='Статус',
    )
    data = models.JSONField(
        default=dict,
        verbose_name='Данные',
        db_comment='Данные'
    )

    def __str__(self) -> str:
        return f'Подводная часть (статус): {self.status}'

    class Meta:
        verbose_name = 'настройку для подводной части'
        verbose_name_plural = 'Настройки для подводной части'


class BestStartReaction(models.Model):
    """Настройки для лучшей стартовой реакции."""

    parsing_session = models.ForeignKey(
        ParsingSession,
        on_delete=models.CASCADE,
        verbose_name='Сессия парсинга',
        db_comment='Сессия парсинга',
    )
    status = models.BooleanField(
        default=True,
        null=False,
        verbose_name='Статус',
        db_comment='Статус',
    )

    def __str__(self) -> str:
        return f'Лучшая стартовая реакция (статус): {self.status}'

    class Meta:
        verbose_name = 'настройку для лучшей стартовой реакции'
        verbose_name_plural = 'Настройки для лучшей стартовой реакции'


class BestStartFinishPercentage(models.Model):
    """
    Настройки для лучшего процента изменения
    стартового и финишного отрезков.
    """

    parsing_session = models.ForeignKey(
        ParsingSession,
        on_delete=models.CASCADE,
        verbose_name='Сессия парсинга',
        db_comment='Сессия парсинга',
    )
    status = models.BooleanField(
        default=True,

swim_graph/parsing/forms.py
from django import forms
from .models import ParsingSession
from swim_graph_utils import constants


class UploadFileForm(forms.Form):
    "Форма для загрузки файлов."
    link_video = forms.URLField(
        label='Укажите ссылку на видео:',
        required=True,
        widget=forms.URLInput(
            attrs={'class': 'form-control border-primary'}
        )
    )
    start_list_file = forms.FileField(
        label='Загрузите стартовый протокол:',
        required=True,
        widget=forms.ClearableFileInput(
            attrs={'class': 'form-control-file'}
        )
    )
    results_file = forms.FileField(
        label='Загрузите финальный протокол:',
        required=True,
        widget=forms.ClearableFileInput(
            attrs={'class': 'form-control-file'}
        )
    )


class ReportSetupForm(forms.Form):
    "Форма настройки отчета"
    file_name = forms.CharField(
        max_length=256,
        label='Название отчета:',
        required=True,
        widget=forms.TextInput(
            attrs={'class': 'form-control border-primary'}
        )
    )
    swim_length = forms.ChoiceField(
        choices=constants.SwimLength.choices(),
        label='Длина заплыва:',
        required=True,
        widget=forms.Select(
            attrs={'class': 'form-control border-primary'}
        )
    )
    pool_length = forms.ChoiceField(
        choices=constants.PoolLength.choices(),
        label='Метраж бассейна:',
        required=True,
        widget=forms.Select(
            attrs={'class': 'form-control border-primary'}
        )
    )

    # 1. Стартовый отрезок
    status_start_distance = forms.BooleanField(
        required=False,
        label='Включать в отчет',
        initial=True,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input',
                   'role': 'switch'}
            )
    )

    # 2. Средняя скорость каждые 25/50 м
    status_average_speed = forms.BooleanField(
        required=False,
        label='Включать в отчет',
        initial=True,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input',
                   'role': 'switch'}
            )
    )

    # 3. Количество циклов на лучшем отрезке
    status_number_cycles = forms.BooleanField(
        required=False,
        label='Включать в отчет',
        initial=True,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input',
                   'role': 'switch'}
            )
    )

    # 4. Темп на лучшем отрезке
    status_pace = forms.BooleanField(
        required=False,
        label='Включать в отчет',
        initial=True,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input',
                   'role': 'switch'}
            )
    )

    # 5. Падение скорости каждые 25/50 м
    status_speed_drop = forms.BooleanField(
        required=False,
        label='Включать в отчет',
        initial=True,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input',
                   'role': 'switch'}
            )
    )

    # 6. Отставание от лидера каждые 25/50 м
    status_leader_gap = forms.BooleanField(
        required=False,
        label='Включать в отчет',
        initial=True,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input',
                   'role': 'switch'}
            )
    )

    # 7. Подводная часть
    status_underwater_part = forms.BooleanField(
        required=False,
        label='Включать в отчет',
        initial=True,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input',
                   'role': 'switch'}
            )
    )

    # 8. Лучшая стартовая реакция
    status_best_start_reaction = forms.BooleanField(
        required=False,
        label='Включать в отчет',
        initial=True,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input',
                   'role': 'switch'}
            )
    )

    # 9. Лучший процент изменения стартового и финишного отрезков
    status_best_start_finish_percentage = forms.BooleanField(
        required=False,
        label='Включать в отчет',
        initial=True,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input',
                   'role': 'switch'}
            )
    )

    # 10. Тепловая карта
    status_heat_map = forms.BooleanField(
        required=False,
        label='Включать в отчет',
        initial=True,
        widget=forms.CheckboxInput(
            attrs={'class': 'form-check-input',
                   'role': 'switch'}
            )
    )

swim_graph/parsing/templates/parsing/heatmap.html
{% extends 'swim_graph/base.html' %}

{% block content %}
<div class="container mt-4">
    <h2>Тепловая карта</h2>
    <div>
        {{ graph|safe }}
    </div>
</div>
{% endblock %}

swim_graph/parsing/templates/parsing/report.html
{% extends 'swim_graph/base.html' %}

{% load static %}

{% load custom_filters %}

{% block content %}
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            {% endfor %}
        </div>
    {% endif %}
    {% csrf_token %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-2">
                <nav>
                    <ul class="nav nav-pills">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Таблицы и диаграммы</a>
                            <ul class="dropdown-menu">
                                {% if active_settings.status_start_distance %}
                                    <li><a class="dropdown-item" href="#list-item-1">Стартовый отрезок</a></li>
                                {% endif %}
                                {% if active_settings.status_average_speed %}
                                    <li><a class="dropdown-item" href="#list-item-2">Средняя скорость каждые {{ session.pool_length }}</a></li>
                                {% endif %}
                                {% if active_settings.status_number_cycles %}
                                    <li><a class="dropdown-item" href="#list-item-3">Кол-во циклов на лучшем отрезке</a></li>
                                {% endif %}
                                {% if active_settings.status_pace %}
                                    <li><a class="dropdown-item" href="#list-item-4">Темп на лучшем отрезке</a></li>
                                {% endif %}
                                {% if active_settings.status_speed_drop %}
                                    <li><a class="dropdown-item" href="#list-item-5">Падение скорости каждые {{ session.pool_length }}</a></li>
                                {% endif %}
                                {% if active_settings.status_leader_gap %}
                                    <li><a class="dropdown-item" href="#list-item-6">Отставание от лидера каждые {{ session.pool_length }}</a></li>
                                {% endif %}
                                {% if active_settings.status_underwater_part %}
                                    <li><a class="dropdown-item" href="#list-item-7">Подводная часть</a></li>
                                {% endif %}
                                {% if active_settings.status_best_start_reaction %}
                                    <li><a class="dropdown-item" href="#list-item-8">Лучшая стартовая реакция</a></li>
                                {% endif %}
                                {% if active_settings.status_best_start_finish_percentage %}
                                    <li><a class="dropdown-item" href="#list-item-9">Лучший процент изменения стартового и финишного отрезков</a></li>
                                {% endif %}
                                {% if active_settings.status_heat_map %}
                                    <li><a class="dropdown-item" href="#list-item-10">Тепловая карта</a></li>
                                {% endif %}
                                    <li><a class="dropdown-item" href="#list-item-11">Результаты заплыва</a></li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
            <div class="col-8">
                <h3 class="mb-2 text-center"> {{ session.file_name }} </h3>
            </div>
            <div class="col-2">
                <div class="d-grid justify-content-md-end">
                    <a href="{% url 'report_setup' session.id %}" class="btn btn-primary btn-small">Настройки отчета</a>
                </div>
            </div>
        </div>
        <div class="row justify-content-center mt-2">
            <div data-bs-spy="scroll" data-bs-target="#list-example" data-bs-smooth-scroll="true" class="scrollspy-example" tabindex="0">
                {% if active_settings.status_start_distance %}
                    <div class="card border-secondary" id="list-item-1">
                        <h4 class="card-header">Стартовый отрезок</h4>
                        <div class="card-body">
                            {{ tables.start_distance_table|safe }}
                        </div>
                    </div>
                {% endif %}
                {% if active_settings.status_average_speed %}
                    <div class="card border-secondary mt-1" id="list-item-2">
                        <h4 class="card-header">Средняя скорость каждые {{ session.pool_length }}</h4>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item chart-container">
                                {{ charts.average_speed_chart|safe }}
                            </li>
                            <li class="list-group-item">
                                {{ tables.average_speed_table|safe }}
                            </li>
                        </ul>
                    </div>
                {% endif %}
                {% if active_settings.status_number_cycles %}
                    <div class="card border-secondary mt-1" id="list-item-3">
                        <h4 class="card-header">Кол-во циклов на лучшем отрезке</h4>
                        <div class="card-body">
                            {{ charts.number_cycles_chart|safe }}
                        </div>
                    </div>
                {% endif %}
                {% if active_settings.status_pace %}
                    <div class="card border-secondary mt-1" id="list-item-4">
                        <h4 class="card-header">Темп на лучшем отрезке</h4>
                        <div class="card-body">
                            {{ tables.pace_table|safe }}
                        </div>
                    </div>
                {% endif %}
                {% if active_settings.status_speed_drop %}
                    <div class="card border-secondary mt-1" id="list-item-5">
                        <h4 class="card-header">Падение скорости каждые {{ session.pool_length }}</h4>
                        <div class="card-body">
                            {{ tables.speed_drop_table|safe }}
                        </div>
                    </div>
                {% endif %}
                {% if active_settings.status_leader_gap %}
                    <div class="card border-secondary mt-1" id="list-item-6">
                        <h4 class="card-header">Отставание от лидера каждые {{ session.pool_length }}</h4>
                        <div class="card-body">
                            {{ tables.leader_gap_table|safe }}
                        </div>
                    </div>
                {% endif %}
                {% if active_settings.status_underwater_part %}
                    <div class="card border-secondary mt-1" id="list-item-7">
                        <h4 class="card-header">Подводная часть</h4>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item chart-container">
                                {{ charts.underwater_part_chart|safe }}
                            </li>
                            <li class="list-group-item">
                                {{ tables.underwater_part_table|safe }}
                            </li>
                        </ul>
                    </div>
                {% endif %}
                {% if active_settings.status_best_start_reaction %}
                    <div class="card border-secondary mt-1" id="list-item-8">
                        <h4 class="card-header">Лучшая стартовая реакция</h4>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item chart-container">
                                {{ charts.start_reaction_chart|safe }}
                            </li>
                            <li class="list-group-item">
                                {{ tables.start_reaction_table|safe }}
                            </li>
                        </ul>
                    </div>
                {% endif %}
                {% if active_settings.status_best_start_finish_percentage %}
                    <div class="card border-secondary mt-1" id="list-item-9">
                        <h4 class="card-header">Лучший процент изменения стартового и финишного отрезков</h4>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item chart-container">
                                {{ charts.start_finish_difference_chart|safe }}
                            </li>
                            <li class="list-group-item">
                                {{ tables.start_finish_difference_table|safe }}
                            </li>
                        </ul>
                    </div>
                {% endif %}
                {% if active_settings.status_heat_map %}
                    <div class="card border-secondary mt-1" id="list-item-10">
                        <h4 class="card-header">Тепловая карта</h4>
                        <div class="card-body">
                            {{ charts.heat_map_chart|safe }}
                        </div>
                    </div>
                {% endif %}
                <div class="card border-secondary mt-1" id="list-item-11">
                    <h4 class="card-header">Результаты заплыва</h4>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th style='width: 20px;'>Финишная позиция</th>
                                        <th style='width: 20px;'>Стартовая позиция</th>
                                        <th>Фамилия Имя</th>
                                        <th>Время реакции</th>
                                        <th>Результат</th>
                                        <th>Очки</th>
                                        {% with first_participant=protocol_data.0 %}
                                            {% for split_time in first_participant.swimsplittime_set.all %}
                                                <th>{{ split_time.distance }}</th>
                                            {% endfor %}
                                        {% endwith %}
                                    </tr>
                                </thead>
                                <tbody class="text-center align-middle">
                                    {% for participant in protocol_data %}
                                        <tr>
                                            <td>{{ participant.final_position }}</td>
                                            <td>{{ participant.start_position }}</td>
                                            <td>{{ participant.initials }}</td>
                                            <td>{{ participant.reaction_time|time_format }}</td>
                                            <td>{{ participant.result|time_format }}</td>
                                            <td>{{ participant.points }}</td>
                                            {% for split_time in participant.swimsplittime_set.all %}
                                                <td>{{ split_time.split_time|time_format }}</td>
                                            {% endfor %}
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <button id="scrollToTopBtn" class="scroll-to-top">&#8679;</button>
    <br/>

    {% block extra_js %}
        <script src="{% static 'js/scroll_to_top.js' %}"></script>
    {% endblock %}

{% endblock %}

swim_graph/parsing/templates/parsing/upload.html
{% extends 'swim_graph/base.html' %}

{% load static %}

{% load custom_filters %}

{% block content %}
    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show text-center {{ message.extra_tags }}" role="alert" {% endif %}>
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                    </button>
                </div>
            {% endfor %}
        </div>
    {% endif %}

    <div class="container mt-4">
        <div class="row justify-content-center mt-2">
            <div class="col-6 align-self-center">
                <h3 class="mb-4 text-center">Загрузить протоколы</h2>
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="card border-primary">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item bg-light">
                                <label class="form-label">
                                    <strong>{{ form.link_video.label }}</strong>
                                </label>
                                {{ form.link_video }}
                            </li>
                            <li class="list-group-item bg-light">
                                <label class="form-label">
                                    <strong>{{ form.start_list_file.label }}</strong>
                                </label>
                                <br />
                                {{ form.start_list_file }}
                            </li>
                            <li class="list-group-item bg-light">
                                <label class="form-label">
                                    <strong>{{ form.results_file.label }}</strong>
                                </label>
                                <br />
                                {{ form.results_file }}
                            </li>
                        </ul>
                    </div>
                    <div class="d-grid justify-content-md-end">
                        <button type="submit" class="btn btn-secondary mt-2">Продолжить</button>
                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock %}